language: generic
sudo: required
services:
  - docker

# before_install:
#   - docker build -t al1awlam/react-test -f  ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true al1awlam/react-test npm test

after_success:
  - docker build -t al1awlam/multi-client ./client
  - docker build -t al1awlam/multi-nginx ./nginx
  - docker build -t al1awlam/multi-server ./server
  - docker build -t al1awlam/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --pasword-stdin

  - docker push al1awlam/multi-client
  - docker push al1awlam/multi-nginx
  - docker push al1awlam/multi-server
  - docker push al1awlam/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-070586096493
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
